/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fwbkesioorqklhlcgmio"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3Ymtlc2lvb3Jxa2xobGNnbWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDkxNzgsImV4cCI6MjA3MDgyNTE3OH0.YWsNJBHYzbm-y-zRNfxRu777qVU_8NYEWmLa62tf-3I"
